admin_business_entities_list:
  path: /
  methods: [ GET ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\BusinessEntity\BusinessEntitiesController::listAction
    _legacy_controller: AdminBusinessEntities
    _legacy_link: AdminBusinessEntities
    _legacy_feature_flag: improved_b2b

admin_business_entities_filter:
  path: /
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\CommonController::searchGridAction
    _legacy_controller: AdminBusinessEntities
    _legacy_link: AdminBusinessEntities
    _legacy_feature_flag: improved_b2b
    gridDefinitionFactoryServiceId: PrestaShop\PrestaShop\Core\Grid\Definition\Factory\BusinessEntityGridDefinitionFactory
    redirectRoute: admin_business_entities_list

admin_business_entities_view:
  path: /{businessEntityId}/view
  methods: [ GET ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\BusinessEntity\BusinessEntitiesController::viewAction
    _legacy_controller: AdminBusinessEntities
    _legacy_link: AdminBusinessEntities:view
    _legacy_feature_flag: improved_b2b
  requirements:
    businessEntityId: \d+

admin_business_entities_delete:
  path: /delete/{businessEntityId}
  methods: [ DELETE ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\BusinessEntity\BusinessEntitiesController::deleteAction
    _legacy_controller: AdminBusinessEntities
    _legacy_link: AdminBusinessEntities:delete
    _legacy_feature_flag: improved_b2b
  requirements:
    businessEntityId: \d+

admin_business_entities_customer_b2b_filter:
  path: /{businessEntityId}/customers/filter
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\BusinessEntity\BusinessEntitiesController::filterCustomerB2BAction
    _legacy_controller: AdminBusinessEntities
    _legacy_link: AdminBusinessEntities:filterCustomerB2B
    _legacy_feature_flag: improved_b2b
  requirements:
    businessEntityId: \d+

admin_business_entities_check_duplicate_identifier:
  path: /check-duplicate-identifier
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\BusinessEntity\BusinessEntitiesController::checkDuplicateIdentifierAction
    _legacy_controller: AdminBusinessEntities
    _legacy_link: AdminBusinessEntities:checkDuplicateIdentifier
    _legacy_feature_flag: improved_b2b

admin_business_entities_bulk_delete:
  path: /bulk-delete
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\BusinessEntity\BusinessEntitiesController::bulkDeleteAction
    _legacy_controller: AdminBusinessEntities
    _legacy_link: AdminBusinessEntities:bulkDelete
    _legacy_feature_flag: improved_b2b

admin_business_entities_create:
  path: /new
  methods: [ GET, POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\BusinessEntity\BusinessEntitiesController::createAction
    _legacy_controller: AdminBusinessEntities
    _legacy_link: AdminBusinessEntities:create
    _legacy_feature_flag: improved_b2b

admin_business_entities_edit:
  path: /{businessEntityId}/edit
  methods: [ GET, POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\BusinessEntity\BusinessEntitiesController::editAction
    _legacy_controller: AdminBusinessEntities
    _legacy_link: AdminBusinessEntities:update
    _legacy_feature_flag: improved_b2b
  requirements:
    businessEntityId: \d+
