admin_business_entities_list:
  path: /
  methods: [ GET ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\BusinessEntity\BusinessEntitiesController::listAction

admin_business_entities_filter:
  path: /
  methods: [POST]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\CommonController::searchGridAction
    _legacy_controller: AdminBusinessEntities
    _legacy_link: AdminBusinessEntities
    _legacy_feature_flag: improved_b2b
    gridDefinitionFactoryServiceId: prestashop.core.grid.definition.factory.business_entity
    redirectRoute: admin_business_entities_list

admin_business_entities_view:
  path: /{businessEntityId}/view
  methods: [ GET ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\BusinessEntity\BusinessEntitiesController::viewAction
    _legacy_controller: AdminBusinessEntities
    _legacy_link: AdminBusinessEntities:view
    _legacy_feature_flag: improved_b2b
  requirements:
    businessEntityId: \d+

admin_business_entities_customer_b2b_filter:
  path: /{businessEntityId}/customers/filter
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\BusinessEntity\BusinessEntitiesController::filterCustomerB2BAction
    _legacy_controller: AdminBusinessEntities
    _legacy_link: AdminBusinessEntities:filterCustomerB2B
    _legacy_feature_flag: improved_b2b
  requirements:
    businessEntityId: \d+

admin_business_entities_bulk_delete:
  path: /bulk-delete
  methods: [ POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\BusinessEntity\BusinessEntitiesController::bulkDeleteAction
    _legacy_controller: AdminBusinessEntities
    _legacy_link: AdminBusinessEntities:bulkDelete
    _legacy_feature_flag: improved_b2b

admin_business_entities_create:
  path: /new
  methods: [ GET, POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\BusinessEntity\BusinessEntitiesController::createAction

admin_business_entities_edit:
  path: /{businessEntityId}/edit
  methods: [ GET, POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\BusinessEntity\BusinessEntitiesController::editAction
    _legacy_controller: AdminBusinessEntities
    _legacy_link: AdminBusinessEntities:update
    _legacy_feature_flag: improved_b2b
  requirements:
    businessEntityId: \d+

admin_simple_customer_b2b_toggle_status:
  path: /{customerB2bId}/toggle-status
  methods: [ GET ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\BusinessEntity\CustomerB2BController::toggleStatusAction
    _legacy_controller: AdminCustomerB2B
    _legacy_link: AdminCustomerB2B:toggleStatus
    _legacy_feature_flag: improved_b2b
  requirements:
    customerB2bId: \d+

admin_simple_customer_b2b_view:
  path: /{customerB2bId}/view
  methods: [ GET ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\BusinessEntity\CustomerB2BController::viewAction
    _legacy_controller: AdminCustomerB2B
    _legacy_link: AdminCustomerB2B:view
    _legacy_feature_flag: improved_b2b
  requirements:
    customerB2bId: \d+

admin_customer_b2b_create:
  path: /new
  methods: [ GET, POST ]
  defaults:
    _controller: PrestaShopBundle\Controller\Admin\Sell\BusinessEntity\CustomerB2BController::createAction
    _legacy_controller: AdminCustomerB2B
    _legacy_link: AdminCustomerB2B:create
    _legacy_feature_flag: improved_b2b
