services:
  _defaults:
    public: true
    autowire: true

  PrestaShop\PrestaShop\Core\Grid\Definition\Factory\BusinessEntityGridDefinitionFactory:
    calls:
      - [ setTranslator, [ '@translator' ] ]
    tags:
      - { name: core.grid_definition_factory }

  PrestaShop\PrestaShop\Core\Grid\Query\BusinessEntityQueryBuilder:
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'

  PrestaShop\PrestaShop\Adapter\BusinessEntity\QueryHandler\GetBusinessEntityForViewingHandler:
    autoconfigure: true
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'
      $defaultLanguageContext: '@prestashop.default.language.context'

  prestashop.core.grid.data.factory.business_entity:
    class: PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory
    arguments:
      - '@PrestaShop\PrestaShop\Core\Grid\Query\BusinessEntityQueryBuilder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'business_entity'

  prestashop.core.grid.grid_factory.business_entity:
    class: PrestaShop\PrestaShop\Core\Grid\GridFactory
    arguments:
      - '@PrestaShop\PrestaShop\Core\Grid\Definition\Factory\BusinessEntityGridDefinitionFactory'
      - '@prestashop.core.grid.data.factory.business_entity'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'

  PrestaShopBundle\Entity\Repository\BusinessEntityRepository:
    factory: [ '@doctrine.orm.entity_manager', getRepository ]
    arguments:
      - PrestaShopBundle\Entity\B2B\BusinessEntity

  PrestaShop\PrestaShop\Core\Grid\Query\CustomerB2BQueryBuilder:
    arguments:
      $connection: '@doctrine.dbal.default_connection'
      $dbPrefix: '%database_prefix%'

  prestashop.core.grid.definition.factory.simple_customer_b2b_grid_definition_factory:
    class: PrestaShop\PrestaShop\Core\Grid\Definition\Factory\SimpleCustomerB2BGridDefinitionFactory
    arguments:
      $hookDispatcher: '@prestashop.core.hook.dispatcher'
    calls:
      - [ setTranslator, [ '@translator' ] ]
    tags:
      - { name: core.grid_definition_factory }

  prestashop.core.grid.data.factory.customer_b2b:
    class: PrestaShop\PrestaShop\Core\Grid\Data\Factory\DoctrineGridDataFactory
    arguments:
      - '@PrestaShop\PrestaShop\Core\Grid\Query\CustomerB2BQueryBuilder'
      - '@prestashop.core.hook.dispatcher'
      - '@prestashop.core.grid.query.doctrine_query_parser'
      - 'simple_customer_b2b'

  prestashop.core.grid.grid_factory.customer_b2b:
    class: PrestaShop\PrestaShop\Core\Grid\GridFactory
    arguments:
      - '@prestashop.core.grid.definition.factory.simple_customer_b2b_grid_definition_factory'
      - '@prestashop.core.grid.data.factory.customer_b2b'
      - '@prestashop.core.grid.filter.form_factory'
      - '@prestashop.core.hook.dispatcher'
